import Layout from "@/components/Layout/Layout";
import Head from "next/head";
import Link from "next/link";
import NewTodoPage from "./Add-newtodo";
import TodoList from "@/components/TodoList/TodoList";


export default function Home() {
  return (
    <>
      <Head>
        <title>Todo list App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <TodoList/>
      {/* <h1>Home page</h1> */}
    </>
  );
}
